"""initial alert storage and audit schema

Revision ID: 9ec2a1b4b3bf
Revises:
Create Date: 2026-08-30 08:31:20.751960

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ec2a1b4b3bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_dedupe_groups",
        sa.Column("group_key", sa.String(length=255), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duplicate_deliveries", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("group_key"),
    )
    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedupe_group_key", sa.String(length=255), nullable=False),
        sa.Column("event_identity", sa.String(length=512), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_level", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("agent_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alerts_dedupe_group_key"), ["dedupe_group_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_event_identity"), ["event_identity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_received_at"), ["received_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_source"), ["source"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=512), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_type"), ["entity_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_occurred_at"), ["occurred_at"], unique=False)

    op.create_table(
        "alert_events",
        sa.Column("event_identity", sa.String(length=512), nullable=False),
        sa.Column("group_key", sa.String(length=255), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("delivery_count", sa.Integer(), nullable=False),
        sa.Column("content_variants", sa.Integer(), nullable=False),
        sa.Column("first_delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.alert_id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_key"], ["alert_dedupe_groups.group_key"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_identity"),
    )
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alert_events_alert_id"), ["alert_id"], unique=True)
        batch_op.create_index(
            "ix_alert_events_group_last_delivered", ["group_key", "last_delivered_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_events_group_last_delivered")
        batch_op.drop_index(batch_op.f("ix_alert_events_alert_id"))

    op.drop_table("alert_events")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_source"))
        batch_op.drop_index(batch_op.f("ix_alerts_rule_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_received_at"))
        batch_op.drop_index(batch_op.f("ix_alerts_event_identity"))
        batch_op.drop_index(batch_op.f("ix_alerts_dedupe_group_key"))
        batch_op.drop_index(batch_op.f("ix_alerts_agent_id"))

    op.drop_table("alerts")
    op.drop_table("alert_dedupe_groups")
    # ### end Alembic commands ###
